@startjson

title Example of JSON Data
{
"user": {
    "name": "Анжеліка",
    "surname": "Гребенік",
    "age": "19",
    "genger": "жінка",
    "e-mail": "fegffdg@gmail.com",
    "phone": "+38083265232"
  },
  "online-order": {
    "full-name": "Гребенік Анжеліка Олександрівна",
    "adress": "Пушкінська 32",
    "count": "2",
    "cost":"120",
    "date": "05.10.2022",
    "e-pay": {
      "fullname-sender": "Іванов Іван Анатолійович",
      "fullname-customer": "Гребенік Анжеліка Олександрівна",
      "account-number": "999429238423643332",
      "sum": "120"
    }
  }
}
@endjson