@startuml
title Usecase for Information system
left to right direction
skinparam packageStyle rect
actor User
actor Homeless_consumer
rectangle Software {
 Homeless_consumer --|> User
 User -- (Authorize the user)
 Homeless_consumer -- (Find housing)

 (Create an order) ..> (Find housing) : <<extend>>
 (Find housing) ..> (Authorize the user) : <<include>>
}
@enduml